/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.*;

/**
 *
 * @author p1402690
 */
public class GestionProduit extends javax.swing.JFrame {

    /**
     * Creates new form GestionProduit
     */
    public GestionProduit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caracteristiquesPanel = new javax.swing.JPanel();
        jtfPrixUnitaire = new javax.swing.JTextField();
        jlLibelle = new javax.swing.JLabel();
        jlCategorie = new javax.swing.JLabel();
        jcbComboBox = new javax.swing.JComboBox();
        jlPrixUnitaire = new javax.swing.JLabel();
        jtfLibelle = new javax.swing.JTextField();
        jbAjouter = new javax.swing.JButton();
        jbSupprimer = new javax.swing.JButton();
        jbModifier = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tabProduits = new javax.swing.JTable();
        jlMessagedErreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Gestion Produit"); // NOI18N
        setResizable(false);

        caracteristiquesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caractéristiques du produit", 0, 0, new java.awt.Font("Tahoma", 2, 11))); // NOI18N

        jlLibelle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlLibelle.setText("Libellé");

        jlCategorie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCategorie.setText("Catégorie");

        jcbComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Appareil Photo", "Casque Audio", "Clavier", "Disque Dur Externe", "Lecteur Audio", "Souris" }));
        jcbComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComboBoxActionPerformed(evt);
            }
        });

        jlPrixUnitaire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPrixUnitaire.setText("Prix unitaire");
        jlPrixUnitaire.setToolTipText("");

        jbAjouter.setText("Ajouter");
        jbAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjouterActionPerformed(evt);
            }
        });

        jbSupprimer.setText("Supprimer");

        jbModifier.setText("Modifier");

        javax.swing.GroupLayout caracteristiquesPanelLayout = new javax.swing.GroupLayout(caracteristiquesPanel);
        caracteristiquesPanel.setLayout(caracteristiquesPanelLayout);
        caracteristiquesPanelLayout.setHorizontalGroup(
            caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caracteristiquesPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caracteristiquesPanelLayout.createSequentialGroup()
                        .addComponent(jbAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jbModifier)
                        .addGap(33, 33, 33)
                        .addComponent(jbSupprimer)
                        .addGap(39, 39, 39))
                    .addGroup(caracteristiquesPanelLayout.createSequentialGroup()
                        .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLibelle)
                            .addComponent(jlCategorie)
                            .addComponent(jlPrixUnitaire))
                        .addGap(54, 54, 54)
                        .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPrixUnitaire)
                            .addComponent(jcbComboBox, 0, 128, Short.MAX_VALUE)
                            .addComponent(jtfLibelle))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        caracteristiquesPanelLayout.setVerticalGroup(
            caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caracteristiquesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlLibelle)
                    .addComponent(jtfLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategorie)
                    .addComponent(jcbComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPrixUnitaire)
                    .addComponent(jtfPrixUnitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(caracteristiquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAjouter)
                    .addComponent(jbSupprimer)
                    .addComponent(jbModifier))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libellé", "Catégorie", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tabProduits);

        jlMessagedErreur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlMessagedErreur.setForeground(new java.awt.Color(255, 0, 0));
        jlMessagedErreur.setText("(Message d'erreur)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caracteristiquesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jlMessagedErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(caracteristiquesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlMessagedErreur)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComboBoxActionPerformed

    private void jbAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjouterActionPerformed
        DefaultTableModel modele = (DefaultTableModel) tabProduits.getModel();
    }//GEN-LAST:event_jbAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel caracteristiquesPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jbAjouter;
    private javax.swing.JButton jbModifier;
    private javax.swing.JButton jbSupprimer;
    private javax.swing.JComboBox jcbComboBox;
    private javax.swing.JLabel jlCategorie;
    private javax.swing.JLabel jlLibelle;
    private javax.swing.JLabel jlMessagedErreur;
    private javax.swing.JLabel jlPrixUnitaire;
    private javax.swing.JTextField jtfLibelle;
    private javax.swing.JTextField jtfPrixUnitaire;
    private javax.swing.JTable tabProduits;
    // End of variables declaration//GEN-END:variables
}
